### ISSUE TITLE
UserIdentity.tokenIdentifier vs UserIdentity.subject in storeUser function

### ISSUE THREAD

**Issue by leodevbro** [get-convex/convex-demos#17]
Here:
https://docs.convex.dev/auth/database-auth

The docs recommend using `identity.tokenIdentifier` to store the **external auth id** into our DB.

But it looks like this:
```javascript
console.log(identity.tokenIdentifier);
logs this:
'https://normal-quagga-15.clerk.accounts.dev|user_2UqFb5XFIur7dYbfl7GuCGoUuRH'
```

Is the left side really needed?

Why don't we do simply this?
```javascript
console.log(identity.subject);
logs this:
'user_2UqFb5XFIur7dYbfl7GuCGoUuRH'
```

I think the `user_2UqFb5XFIur7dYbfl7GuCGoUuRH` is totally unique and enough, right?

**Comment by xixixao** [comment]
If you're using only one provider, you can use `subject`. The left part in `tokenIdentifier` is needed to distinguish keys from two different providers, which might issue the same key:

```
Provider A, Key X
Provider B, Key X
```
