### ISSUE TITLE
uploading an image from native app using upload URL fails

### ISSUE THREAD

**Issue by varand-pez** [get-convex/convex-demos#20]
I'm using Expo and its ImagePicker lib to select an image to upload.
The library return the uri to the image which is in format of `file:///Users/blablabla-lots-of-it/Library/Caches/ImagePicker/F2C150D4-505E-4371-9469-3663B2DA1C9F.jpg`.

with that `storageId` comes back `undefined` always.

Is uploading `via upload URLs` not supported for react-native/expo?

Thanks.

**Comment by nipunn1313** [comment]
Hi. It is supported. The storage upload via upload URL is framework agnostic.

Could you provide your code? What API call(s0) are giving an undefined storageId?

**Comment by varand-pez** [comment]
just ignore it already, it has to be `image/*`

**Comment by nipunn1313** [comment]
there you go! Nice debugging!
