### ISSUE TITLE
why outgoing request timed out?

### ISSUE THREAD

**Issue by essencejay** [get-convex/convex-demos#22]
$ npm run dev

> convex-tour-chat-0@0.0.0 dev
> npm-run-all dev:init --parallel dev:server dev:client

> convex-tour-chat-0@0.0.0 dev:init
> convex dev --run init --until-success

Unexpected Error: RPError: outgoing request timed out after 10000ms
ERROR: "dev:init" exited with 1.

Network:
Unexpected Error: RPError: outgoing request timed out after 10000ms
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: connect ETIMEDOUT 34.120.195.249:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
PS D:\ideas\ai-town> ping 34.120.195.249

正在 Ping 34.120.195.249 具有 32 字节的数据:
来自 34.120.195.249 的回复: 字节=32 时间=190ms TTL=108
来自 34.120.195.249 的回复: 字节=32 时间=154ms TTL=108
来自 34.120.195.249 的回复: 字节=32 时间=199ms TTL=108

**Comment by nipunn1313** [comment]
This tutorial talks to auth0 (the auth provider convex uses to log into your Convex account). It appears that you may have some network connectivity issue in speaking with auth0.

You can try `npx convex login` - which runs just the login portion of the `npm run dev` command to see if you can get that to work on your internet connection.

**Comment by essencejay** [comment]
> This tutorial talks to auth0 (the auth provider convex uses to log into your Convex account). It appears that you may have some network connectivity issue in speaking with auth0.
> 
> You can try `npx convex login` - which runs just the login portion of the `npm run dev` command to see if you can get that to work on your internet connection.

$ npx convex login
Unexpected Error: RPError: outgoing request timed out after 10000ms

Yes, that's the problem

**Comment by nipunn1313** [comment]
It is possible you may be on an internet connection that is running into timeouts when speaking to auth0. You may want to try running from a VPN or improving internet connection or otherwise.

It's also possible there's some kind of firewall blocking openid connection messages from reaching auth0.

**Comment by xixixao** [comment]
Let us know on [Discord](https://convex.dev/community) if you're still having trouble logging in
