### ISSUE TITLE
Clerck and Convex setup in Expo app

### ISSUE THREAD

**Issue by varand-pez** [get-convex/convex-demos#23]
Hi, I'm trying to setup Clerk in my Expo app which uses Convex. [Followed this doc](https://docs.convex.dev/auth/clerk) but I need some help because the app is not coming up. I reached to step 8 and decided to run the app to make sure the wiring is correct.

I have the env variable in `auth.config.js` for `CLERK_JWT_ISSUER_DOMAIN` which that exists in both local `.env` file as well as Convex's Environment Variables in Settings.

I use Expo package instead of react for step 6 from the above doc.
`import { ClerkProvider, useAuth } from "@clerk/clerk-expo";`
`import { ConvexProviderWithClerk } from "convex/react-clerk";`

`CLERK_PUBLISHABLE_KEY` is only in local `.env` file.

The code is wrapped inside these 2 providers.
```
<ClerkProvider publishableKey={CLERK_PUBLISHABLE_KEY}>
  <ConvexProviderWithClerk
    client={convex}
    useAuth={useAuth}
  >
      My initial route stuff...
  </ConvexProviderWithClerk>
</ClerkProvider>
```

The result:

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-16 at 20 39 15](https://github.com/get-convex/convex-demos/assets/47469980/3cf9e2d0-58e0-498d-af72-977800eaa7ef)

Would appreciate any help. I can provide more code snippets but the doc is pretty straightforward.

**Comment by xixixao** [comment]
Hey @varand-pez, to narrow this down, can you follow Clerk docs first and get a working Clerk + Expo setup? Then we can figure out if there's an issue with Convex (which from the error message seems unlikely, as `use0Auth` is not part of Convex).

https://clerk.com/docs/quickstarts/expo

**Comment by varand-pez** [comment]
You can close this issue. there is a conflict between clerk and Expo app router. I decided not to use clerk and but keep the convex.
