### ISSUE TITLE
Error with Next.js rendering

### ISSUE THREAD

**Issue by Openpalms** [get-convex/convex-demos#25]
Next.js is giving an error because UseContext is used with no "use client" in convex node_module
Server Error

Error: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
React
node_modules/convex/dist/esm/react/client.js (281:22)
(rsc)/./node_modules/convex/dist/esm/react/client.js
file:///Users/ga104kin/code/next_project/.next/server/vendor-chunks/convex.js (560:1)

__webpack_require__
file:///Users/ga104kin/code/next_project/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/convex/dist/esm/react/use_queries.js (7:68)
(rsc)/./node_modules/convex/dist/esm/react/use_queries.js
file:///Users/ga104kin/code/next_project/.next/server/vendor-chunks/convex.js (600:1)
__webpack_require__
file:///Users/ga104kin/code/next_project/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/convex/dist/esm/react/use_paginated_query.js (9:73)
(rsc)/./node_modules/convex/dist/esm/react/use_paginated_query.js
file:///Users/ga104kin/code/next_project/.next/server/vendor-chunks/convex.js (590:1)
__webpack_require__
file:///Users/ga104kin/code/next_project/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/convex/dist/esm/react/index.js (20:81)
(rsc)/./node_modules/convex/dist/esm/react/index.js
file:///Users/ga104kin/code/next_project/.next/server/vendor-chunks/convex.js (570:1)
__webpack_require__
file:///Users/ga104kin/code/next_project/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./app/page.tsx (8:70)
(rsc)/./app/page.tsx
file:///Users/ga104kin/code/next_project/.next/server/app/page.js (211:1)
Function.__webpack_require__
file:///Users/ga104kin/code/next_project/.next/server/webpack-runtime.js (33:42)
async ek
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:455662)
async eJ
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:459752)
async eY
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:460227)
async eY
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:460358)
async eK
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:463770)
async
file:///Users/ga104kin/code/next_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (11:464248)

**Comment by xixixao** [comment]
Hey @Openpalms, follow the Next.js quickstart(s): https://docs.convex.dev/quickstart/nextjs
For app router it wraps the convex provider in a client component.
