### ISSUE TITLE
Serving saved images do not work

### ISSUE THREAD

**Issue by varand-pez** [get-convex/convex-demos#26]
I have followed the documentation and was able to save/upload images to storage. 
I'm also successfully read them from storage and receive a `http://...` path but unfortunately that is not understood by Image component of ReactNative or Expo, so the images are not rendered.

```
...
{ imageSrc: await ctx.storage.getUrl(item.photoStorageId) }
...

console.log(imageSrc) 
=> https://graceXXXXXXXXXXXX.cloud/api/storage/XXX0de41-2f6d-XXX-XXXX-d4XXXXXX
```
Please ignore the Xs

Opening that URL in browser downloads a file with a long path to the image, but it's still not rendering any image.

How do I use this (imageSrc) with React Native Image component? 

Thanks.

**Comment by nipunn1313** [comment]
This is a good example app to show how to use the URL.
https://github.com/get-convex/convex-demos/tree/main/file-storage

This example app uses a basic <img> tag, but the same idea should apply for ReactNative <Image> component.
https://github.com/get-convex/convex-demos/blob/main/file-storage/src/App.tsx#L96

**Comment by varand-pez** [comment]
I had already seen that example app, but the Image component and web image tag are not quite the same.
going to discord to resolve this.
thanks you
